#!/usr/bin/env bash
set -Eeuo pipefail

# install-telemt.sh
# Debian/Ubuntu only.

DOMAIN=""
PORT="4444"
PROXY_USER="main"
SECRET=""
BINARY_PATH="/usr/local/bin/telemt"
CONFIG_DIR="/etc/telemt"
CONFIG_PATH="${CONFIG_DIR}/telemt.toml"
SERVICE_PATH="/etc/systemd/system/telemt.service"
API_LISTEN="127.0.0.1:9091"

log() { printf '[%s] %s\n' "$(date +'%F %T')" "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'EOF'
Usage:
  bash install-telemt.sh --domain proxy.example.com [--port 4444] [--user main] [--secret HEX32]

Options:
  --domain   TLS domain to put into [censorship].tls_domain (required)
  --port     Listening TCP port (default: 4444)
  --user     Proxy username inside [access.users] (default: main)
  --secret   32 hex chars; autogenerated if omitted
  -h, --help Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="${2:-}"; shift 2 ;;
    --port) PORT="${2:-}"; shift 2 ;;
    --user) PROXY_USER="${2:-}"; shift 2 ;;
    --secret) SECRET="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ $EUID -eq 0 ]] || die "run as root"
[[ -n "$DOMAIN" ]] || die "--domain is required"
[[ "$PORT" =~ ^[0-9]+$ ]] || die "--port must be numeric"
(( PORT >= 1 && PORT <= 65535 )) || die "--port must be in 1..65535"
[[ "$PROXY_USER" =~ ^[A-Za-z0-9_.-]+$ ]] || die "--user contains invalid characters"

if [[ -n "$SECRET" ]]; then
  [[ "$SECRET" =~ ^[0-9a-fA-F]{32}$ ]] || die "--secret must be exactly 32 hex chars"
  SECRET="$(printf '%s' "$SECRET" | tr 'A-F' 'a-f')"
else
  SECRET="$(python3 - <<'PY'
import os
print(os.urandom(16).hex())
PY
)"
fi

export DEBIAN_FRONTEND=noninteractive

log "Installing dependencies"
apt-get update -y
apt-get install -y curl wget tar jq ca-certificates python3

ARCH="$(uname -m)"
LIBC_FLAVOR="gnu"
if ldd --version 2>&1 | grep -qi musl; then
  LIBC_FLAVOR="musl"
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

URL="https://github.com/telemt/telemt/releases/latest/download/telemt-${ARCH}-linux-${LIBC_FLAVOR}.tar.gz"

log "Downloading telemt from ${URL}"
curl -fsSL "$URL" | tar -xzf - -C "$TMPDIR"

[[ -f "${TMPDIR}/telemt" ]] || die "downloaded archive does not contain 'telemt'"

log "Installing binary to ${BINARY_PATH}"
install -m 0755 "${TMPDIR}/telemt" "${BINARY_PATH}"

log "Ensuring service user exists"
if ! id telemt >/dev/null 2>&1; then
  useradd -d /opt/telemt -m -r -U telemt
fi

log "Creating config directory"
mkdir -p "${CONFIG_DIR}"
chmod 0755 "${CONFIG_DIR}"

cat > "${CONFIG_PATH}" <<EOF
[general]
use_middle_proxy = false

[general.modes]
classic = false
secure = false
tls = true

[server]
port = ${PORT}

[server.api]
enabled = true
listen = "${API_LISTEN}"
whitelist = ["127.0.0.1/32"]
read_only = true

[censorship]
tls_domain = "${DOMAIN}"

[access.users]
${PROXY_USER} = "${SECRET}"
EOF

chown -R telemt:telemt "${CONFIG_DIR}"
chmod 0640 "${CONFIG_PATH}"

cat > "${SERVICE_PATH}" <<EOF
[Unit]
Description=Telemt
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=telemt
Group=telemt
WorkingDirectory=/opt/telemt
ExecStart=${BINARY_PATH} ${CONFIG_PATH}
Restart=on-failure
RestartSec=2
LimitNOFILE=65536
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF

log "Checking whether port ${PORT} is already in use"
if ss -lnt "( sport = :${PORT} )" | grep -q ":${PORT}"; then
  die "port ${PORT} is already in use"
fi

log "Reloading systemd and starting service"
systemctl daemon-reload
systemctl enable --now telemt

sleep 3

log "Service status"
systemctl --no-pager --full status telemt || true

log "Listening sockets"
ss -lntp | grep -E ":${PORT}\b" || true

if command -v ufw >/dev/null 2>&1; then
  if ufw status 2>/dev/null | grep -q "Status: active"; then
    log "Opening port ${PORT}/tcp in ufw"
    ufw allow "${PORT}/tcp" >/dev/null || true
  fi
fi

log "Trying to read generated user links from local API"
if curl -fsS "http://${API_LISTEN}/v1/users" >/dev/null 2>&1; then
  curl -fsS "http://${API_LISTEN}/v1/users" | jq .
else
  log "API not reachable yet; recent logs follow"
  journalctl -u telemt -n 80 --no-pager || true
fi

cat <<EOF

Done.

Config:   ${CONFIG_PATH}
Service:  ${SERVICE_PATH}
Binary:   ${BINARY_PATH}
Port:     ${PORT}
Domain:   ${DOMAIN}
User:     ${PROXY_USER}
Secret:   ${SECRET}

Useful commands:
  systemctl status telemt --no-pager -l
  journalctl -u telemt -n 100 --no-pager
  journalctl -u telemt -f
  curl -s http://${API_LISTEN}/v1/users | jq

EOF
